# Generated by Django 4.2 on 2023-05-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_tutorials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='Student_file',
        ),
    ]
