# Generated by Django 4.2 on 2023-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_tutorials_student_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='Student_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
