# Generated by Django 4.2 on 2023-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_tutorials_student_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='Student_file',
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='teacher_file',
            field=models.FileField(upload_to='pds/teacher/'),
        ),
    ]
