# Generated by Django 4.2 on 2023-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_tutorials_student_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='Student_file',
            field=models.FileField(default=1, upload_to='pds/student/'),
            preserve_default=False,
        ),
    ]
