# Generated by Django 4.2 on 2023-05-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_tutorials_student_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorials',
            old_name='teacher_file',
            new_name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='Student_file',
        ),
    ]
